### ISSUE TITLE
Turn this into a usable CLI tool

### ISSUE THREAD

**Issue by sponja23** [IgnacioPardo/flask_app#1]
https://medium.com/nerd-for-tech/how-to-build-and-distribute-a-cli-tool-with-python-537ae41d9d78

**Comment by IgnacioPardo** [comment]
OG project was [create_flask_app](https://github.com/Creativity-Hub/create_flask_app). May be missing PWA features. This repo is for a quick start boilerplate on replit.com

**Comment by sponja23** [comment]
Maybe you should use [branches](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)
